version: "3"
services: 
    app:
        build: .
        image: genelookup_app
        container_name: genelookup_app
        depends_on:
            - mariadb
        ports:
            - "8080:8080"
        links:
            - mariadb:mariadb
        volumes:
            - .:/srv/app
        env_file: .docker.env
    mariadb:
        image: mariadb:10.1.21
        ports:
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=gene_lookup
            - MYSQL_ROOT_PASSWORD=password
    artisan:
        image: genelookup_app
        container_name: genelookup_artisan
        volumes:
            - .:/srv/app
        entrypoint: [
            "php",
            "/srv/app/artisan"
        ]